version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root#123
      MYSQL_DATABASE: graphql_lesson
    ports: ['3306:3306']
